version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3200:3200"
    volumes:
      - ./:/app
    restart: "unless-stopped"
