version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    restart: "unless-stopped"
