# NodeJS Version 20
FROM node:20.16.0-bookworm-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production

EXPOSE 3200

# Cmd script
CMD ["npm", "run", "start"]
